package main

import (
	"google.golang.org/protobuf/compiler/protogen"
)

var (
	defaultImpports = []string{
		"context",
		"fmt",
		"github.com/gin-gonic/gin",
		"google.golang.org/grpc/codes",
		"google.golang.org/grpc/metadata",
		"google.golang.org/grpc/status",
	}
	imports    = make(map[string]string)
	methodSets = make(map[string]int)
)

// generateFile generates a gin.pb.go file.
func generateFile(gen *protogen.Plugin, file *protogen.File) *protogen.GeneratedFile {
	filename := file.GeneratedFilenamePrefix + ".xorm.pb.go"
	g := gen.NewGeneratedFile(filename, file.GoImportPath)
	g.P("// code generated by github.com/kubegames/protoc-gen-xorm. DO NOT EDIT.")
	g.P()
	g.P("package ", file.GoPackageName)
	g.P(`import "xorm.io/xorm"`)

	for _, message := range file.Messages {
		m := &Message{Name: string(message.GoIdent.GoName)}
		g.P(m.Execute())
	}
	return g
}
